resources:
  - name: gitResource2
    type: GitRepo
    configuration:
      path: lidorv/bbb
      gitProvider: VCS_6
      buildOn:
        pullRequestCreate: true
      branches:
        include: master
  - name: buildInfoResource2
    type: BuildInfo
    configuration:
      sourceArtifactory: Artifactory_6
      buildName: BUILD-A
      buildNumber: $run_number
pipelines:
  - name: Pipeline3
    configuration:
      environmentVariables:
        readOnly:
          CI: "true"
          JFROG_CLI_BUILD_NAME: BUILD-A
          JFROG_CLI_BUILD_NUMBER: $run_number
          JFROG_CLI_BUILD_URL: $step_url
    steps:
      - name: Build
        type: MvnBuild
        configuration:
          mvnCommand: install
          resolverSnapshotRepo: lll
          resolverReleaseRepo: lll
          deployerSnapshotRepo: lll
          deployerReleaseRepo: lll

          environmentVariables:
            JFROG_BUILD_STATUS: PASS
          integrations:
            - name: Artifactory_6
          inputResources:
            - name: gitResource2
        execution:
          onFailure:
            - export JFROG_BUILD_STATUS=FAIL
            - jfrog rt bce
            - jfrog rt bag
            - jfrog rt bp
      - name: PublishBuildInfoStep
        type: PublishBuildInfo
        configuration:
          inputResources:
            - name: gitResource2
          outputResources:
            - name: buildInfoResource2
          inputSteps:
            - name: Build
          forceXrayScan: true
        execution:
          onComplete:
            - update_commit_status gitResource2
